apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - port: 80
      targetPort: {{ .Release.Name }}-port
  type: NodePort
